"""empty message

Revision ID: 727ec4231340
Revises: 
Create Date: 2020-09-29 11:27:58.137231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727ec4231340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('movies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('actors',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='actors_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', name='actors_pkey')
    )
    # ### end Alembic commands ###
